[package]
name = "fm-xml-export-exploder"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs_io = "0.1.7"
rayon = "1.9.0"
quick-xml = { version = "0.31.0", features =["escape-html"] }
regex = "1.10.3"
clap = { version = "4.5.2", features = ["derive"] }
anyhow = "1.0.81"

[dev-dependencies]
walkdir = "2.5.0"
insta = "1.36.1"
similar-asserts = "1.5.0"
